controller_joint_names: ['', 'left_ruddevator_joint', 'right_ruddevator_joint', 'left_aileron_joint', 'right_aileron_joint', 'rotor_0_joint', 'rotor_1_joint', 'rotor_2_joint', 'rotor_3_joint', 'rotor_pusher_joint', ]
